Change session-based probabilistic sampling computation
signalfx/splunk-otel-android pull request #698
Opened 2023-11-28 23:12 UTC by breedx-splk

We stray from the path here a little bit by introducing a bespoke sampler that differs from the upstream implementation. This is a stop-gap temporary measure to better align with web and iOS. Sessions sampling decisions can now be more consistent between the platforms.

See https://github.com/signalfx/splunk-otel-ios/pull/185 for a similar change in iOS that this borrowed from.

2023-11-30 18:47 UTC, johnbley requested changes

2023-11-30 18:47 UTC, johnbley commented on splunk-otel-android/src/main/java/com/splunk/rum/internal/UInt32QuadXorTraceIdRatioSampler.java
> +                        Locale.getDefault(), "UInt32QuadXorTraceIdRatioSampler{radio:%f}", ratio);
s/radio/ratio/

2023-11-30 22:31 UTC, breedx-splk commented on splunk-otel-android/src/main/java/com/splunk/rum/internal/UInt32QuadXorTraceIdRatioSampler.java
> +                        Locale.getDefault(), "UInt32QuadXorTraceIdRatioSampler{radio:%f}", ratio);
📻 oh now I get it.

2023-12-01 13:21 UTC, johnbley approved these changes

2023-12-06 20:55 UTC, merged